{"name": "Логин с неверными credentials", "status": "passed", "description": "Тест логина с неверными учетными данными", "steps": [{"name": "Отправка запроса с неверными данными", "status": "passed", "start": 1756924177046, "stop": 1756924177207}, {"name": "Проверка ошибки авторизации", "status": "passed", "start": 1756924177207, "stop": 1756924177207}], "parameters": [{"name": "invalid_data", "value": "{'email': 'invalid-email', 'password': 'password123'}"}], "start": 1756924177046, "stop": 1756924177208, "uuid": "185968a4-b14a-4c9f-b734-83445ddd0597", "historyId": "5e66083b6b0ecf557c0a3c1376ec1c5f", "testCaseId": "9329ecf4e8dae93c2ec48d7631be1618", "fullName": "tests.test_login_user.TestLoginUser#test_login_invalid_credentials_fails", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "RUMSKLCG1160Z8S"}, {"name": "thread", "value": "11304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}