{"name": "Логин с неверными credentials", "status": "passed", "description": "Тест логина с неверными учетными данными", "steps": [{"name": "Отправка запроса с неверными данными", "status": "passed", "start": 1756924177216, "stop": 1756924177379}, {"name": "Проверка ошибки авторизации", "status": "passed", "start": 1756924177379, "stop": 1756924177379}], "parameters": [{"name": "invalid_data", "value": "{'email': '', 'password': 'password123'}"}], "start": 1756924177216, "stop": 1756924177380, "uuid": "5dbba5d3-d99c-452b-8704-f70a6652ad38", "historyId": "42a99c207eda225b2ac731d54ec2fe58", "testCaseId": "9329ecf4e8dae93c2ec48d7631be1618", "fullName": "tests.test_login_user.TestLoginUser#test_login_invalid_credentials_fails", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "RUMSKLCG1160Z8S"}, {"name": "thread", "value": "11304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}